### ISSUE TITLE
MissingMethodException when using bulk rename

### ISSUE THREAD

**Issue by nonamethanks** [architdate/PokeFilename#7]
Trying to use the Bulk Rename on a folder of folders of pk8 files returns this error:
```
System.MissingMethodException: Method not found: 'Boolean PKHeX.Core.PKX.IsPKM(Int64)'.
   at PokeFilename.API.BulkRename.RenameAll(IReadOnlyList`1 files, IFileNamer`1 namer)
   at PokeFilename.API.BulkRename.RenameFolder(String path, IFileNamer`1 namer, Boolean deep)
   at PokeFilename.API.BulkRename.RenameFolder(String path, Boolean deep)
   at PokeFilename.SettingsForm.B_BulkRename_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by architdate** [comment]
Handled in the latest commit! Thanks!
